const types = {
  GUITAR_INVENTORY_DISPLAY: "GUITAR_INVENTORY_DISPLAY",
  API_IS_LOADING: "API_IS_LOADING",
  EQUIPMENT_INVENTORY_DISPLAY: "EQUIPMENT_INVENTORY_DISPLAY",
  TOGGLE_INVENTORY_CHECKBOX: "TOGGLE_INVENTORY_CHECKBOX",
  AMPLIFIER_INVENTORY_DISPLAY: "AMPLIFIER_INVENTORY_DISPLAY",
  EQUIPMENT_DETAILS_DISPLAY: "EQUIPMENT_DETAILS_DISPLAY",
};

export { types };
