const GUITAR_INVENTORY_ACTION_TYPE = {
  GUITAR_INVENTORY: "GUITAR_INVENTORY",
  ADD_GUITAR_INVENTORY_TO_STATE: "ADD_GUITAR_INVENTORY_TO_STATE",
  AMP_INVENTORY: "GUITAR_INVENTORY",
  ADD_AMP_INVENTORY_TO_STATE: "ADD_AMP_INVENTORY_TO_STATE",
  IS_API_DONE_LOADING: "IS_API_DONE_LOADING",
  SET_SELECTED_ID: "SET_SELECTED_ID",
};

const AMPLIFIER_INVENTORY_ACTION_TYPE = {
  AMPLIFIER_INVENTORY: "AMPLIFIER_INVENTORY",
  ADD_AMPLIFIER_INVENTORY_TO_STATE: "ADD_AMPLIFIER_INVENTORY_TO_STATE",
  AMP_INVENTORY: "AMP_INVENTORY",
  ADD_AMP_INVENTORY_TO_STATE: "ADD_AMP_INVENTORY_TO_STATE",
};

const EQUIPMENT_INVENTORY_ACTION_TYPE = {
  ADD_EQUIPMENT_INVENTORY_TO_STATE: "ADD_EQUIPMENT_INVENTORY_TO_STATE",
};

const EQUIPMENT_CHECKBOX_TOGGLE_ACTION_TYPE = {
  EQUIPMENT_CHECKBOX_TOGGLE: "EQUIPMENT_CHECKBOX_TOGGLE",
  ADD_EQUIPMENT_DISPLAY_TOGGLE_TO_STATE:
    "ADD_EQUIPMENT_DISPLAY_TOGGLE_TO_STATE",
};

const DISPLAY_DETAILS_ACTION_TYPE = {
  DISPLAY_AMPLIFIER_DETAILS: "DISPLAY_AMPLIFIER_DETAILS",
  DISPLAY_GUITAR_DETAILS: "DISPLAY_GUITAR_DETAILS",
};
export {
  GUITAR_INVENTORY_ACTION_TYPE,
  EQUIPMENT_INVENTORY_ACTION_TYPE,
  EQUIPMENT_CHECKBOX_TOGGLE_ACTION_TYPE,
  AMPLIFIER_INVENTORY_ACTION_TYPE,
  DISPLAY_DETAILS_ACTION_TYPE,
};
