const GUITAR_INVENTORY_ACTION_TYPE = {
    GUITAR_INVENTORY: 'GUITAR_INVENTORY',
    ADD_GUITAR_INVENTORY_TO_STATE: 'ADD_GUITAR_INVENTORY_TO_STATE',
    IS_API_DONE_LOADING: 'IS_API_DONE_LOADING'
}

export {
    GUITAR_INVENTORY_ACTION_TYPE,
}
